### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by tgrymatt** [PhotoboothProject/photobooth#1010]
### Is your feature request related to a problem?

Yes

### Description

Downloading the photo via the Photo Booth machine's own WLAN

### Describe the solution you'd like

The photobooth doesn't always have internet or, more importantly, you don't always want your guests to be on the same network as the photo booth.

It would therefore be good to have a function that allows the photobooth to set up a WLAN itself without a password, with a generously dimensioned DHCP pool so that the devices that connect immediately receive an IP address. Then you could reach the web server via this Photobooth WLAN and download the photos when you scan the QR code.

### Describe alternatives you've considered

.

**Comment by andi34** [comment]
That's an OS specific feature and can't be solved by Photobooth. On PiOS you can do that easily.

**Comment by andi34** [comment]
https://youtu.be/L4ArdfS87j8?feature=shared
