### ISSUE TITLE
[FEATURE]: QR Code Bottom Corner

### ISSUE THREAD

**Issue by CaptainCookLP** [PhotoboothProject/photobooth#107]
### Is your feature request related to a problem?

No

### Description

Option to show the QR Code directly in the Corner of Picture View.
No need to Press the Button first

### Describe the solution you'd like

QR Code in the Bottom Left Corner

### Describe alternatives you've considered

None

**Comment by andi34** [comment]
One user implemented it months ago, still waiting for the code changes to take a look at ...

**Comment by andi34** [comment]
Todo
