### ISSUE TITLE
[BUG]: label of translated buttons do not fit

### ISSUE THREAD

**Issue by mart-e** [PhotoboothProject/photobooth#135]
### Describe the bug

When using the photobooth in French, there is a few terms that do not fit the buttons box
![Screenshot 2023-02-13 at 09-09-18 Photobooth](https://user-images.githubusercontent.com/564822/218416702-188d0d3f-0511-4fe3-83be-27528f24638f.png)
![Screenshot 2023-02-13 at 09-09-04 Photobooth](https://user-images.githubusercontent.com/564822/218416711-bb9d65af-096b-4d18-bf4f-389f372fa820.png)

Is it something to fix at the translation levels (I am ready to help) or at the CSS (not sure here) ?

### Steps to reproduce the behavior

1. Switch the interface to French
2. Go to home screen, take a picture,...

### Expected behavior

Everything fits the UI

### Photobooth Version

4295699a739cc50eee2aae7fedc54a21d36ee714

### Browser and browser version

Firefox 109

### Operating System

Raspbianlite

### Did it work before?

No

**Comment by andi34** [comment]
Ia it possible to use a shorter text? If yes please join us at crowdin and suggest a new translation.
https://crowdin.com/project/photobooth

**Comment by mart-e** [comment]
I am already member of the crowdin team, will suggest translations :)
I just wanted to be sure if we try to fix it at the translation level or css.

When are the translation fetched ? I see the "Collage -> Photomontage" string was alrady fixed one month ago (probably for that reason).
https://crowdin.com/translate/photobooth/2/en-fr#1286

Side-question : is it best I run on the dev version (as offered by the [install instructions](https://photoboothproject.github.io/Installation-on-Debian)) or the latest stable ?

**Comment by andi34** [comment]
I am trying to sync the translations next days. Currently the monthly import via GitHub is broken and need to be fixed... Need some time to investigate.

Latest dev branch always contains improvements, sometimes new features and small Bugfixes for latest stable version.
Currently there's some changes I'd like to finish to place a new stable release, but private life had some other plans for me last week's... Hope to get things sorted this month.

**Comment by andi34** [comment]
But if you like to adjust the css too, I'd be glad to review a Pullrequest with needed changes.

**Comment by mart-e** [comment]
No problem, take your time, just wanted to be sure I contributed at the right place.
Thanks for making that project :)
