### ISSUE TITLE
[FEATURE]: Public Gallery

### ISSUE THREAD

**Issue by meifi** [PhotoboothProject/photobooth#138]
### Is your feature request related to a problem?

No

### Description

It is posible to create a api connection to lychee ? So it is posible to upload all photos in a new album ... 
https://lycheeorg.github.io/docs/api.html

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by andi34** [comment]
You could use the post-photo command to upload pictures via command line/ executing an bash script which can be more complex. Transferring images could be done via scp for example https://linuxize.com/post/how-to-use-scp-command-to-securely-transfer-files/

There's some more great OpenSource gallery applications available besides Lychee which might need a own implementation. If someone likes to take this advantage and is able to implement it I am glad to review needed changes.

**Comment by jereminius** [comment]
I made it work for myself @meifi. No guarantees, take it as an inspiration if it doesnt work for you 😸 

https://github.com/jereminius/photobooth-lychee-upload

**Comment by andi34** [comment]
Nextcloud will be supported soon:
https://github.com/PhotoboothProject/photobooth/pull/208
