### ISSUE TITLE
[BUG]: Email entry dialog does not extend post-capture image time

### ISSUE THREAD

**Issue by JasonTarka** [PhotoboothProject/photobooth#225]
### Describe the bug

For normal photos you may want to set the post-capture viewing time relatively short (eg: 10-20 seconds), but someone may want to email it to themselves. Especially when using an onscreen keyboard, it takes most people longer than this to enter their email address, so the photobooth suddenly returns to the home screen while they're still typing.

As it stands, the only way to give people enough time to type their address is to set an unreasonably long delay (eg: 1-2 minutes)

### Steps to reproduce the behavior

1. From the Admin panel:
    - Set "Show image after capture" to 10 seconds
    - Enable "Use email"
2. Return to the main photobooth screen
3. Take a photo
4. Tap the "Email" button, see the email entry dialog pop up
    - Side note: This should focus on the text field automatically, rather than requiring the user to click it.
5. Start entering your email, but take more than 10 seconds.

### Expected behavior

One of:

1. Timeout is completely disabled while the email entry is shown, and resumed after email is sent.
2. Timeout is extended by a reasonable (or configurable) delay when the dialog is opened (eg: 2 minutes), and returns to normal when it's closed.
3. Timeout is reset after all interactions with the email entry dialog. eg: Opening, typing a letter, clicking send, etc.

Personally I think #3 may be the ideal so the timeout can still be set reasonable short, but if the user walks away then the post-view is still ended.

### Photobooth Version

8265332b0fa1041b52a970785b38ea13be3332a1

### Browser and browser version

Chrome

### Operating System

Raspberry Pi OS with desktop

### Did it work before?

No

**Comment by andi34** [comment]
Hey and thanks for the report. Please test https://github.com/PhotoboothProject/photobooth/pull/226 and let me know if it solves the issue.

Best regards

Andi
