### ISSUE TITLE
[Question]: Print Support

### ISSUE THREAD

**Issue by capsload2** [PhotoboothProject/photobooth#227]
### Is your feature request related to a problem?

No

### Description

Is there a way to print the snapshits directly with a supported printer?

### Describe the solution you'd like

Support printers

### Describe alternatives you've considered

—-

**Comment by andi34** [comment]
Yes. On linux you can use CUPS to setup your printer. Photobooth can execute a command, print is possible via via `lp` command for example. Example command is added by default via config and can be changed inside Adminpanel. See commands section.

It's an option to print the image immediately after it was taken, else you can enable a print Button as needed.

How to setup a printer isn't part of Photobooth. If you need any help I am sure someone is able to help you in our telegram group.

**Comment by andi34** [comment]
![Screenshot_20230613-123758~2](https://github.com/PhotoboothProject/photobooth/assets/6080900/1f45f9f6-31e8-470b-9ddb-69303a4a74d7)
