### ISSUE TITLE
[FEATURE]: Bulk download for photos in gallery

### ISSUE THREAD

**Issue by floviolleau** [PhotoboothProject/photobooth#234]
### Is your feature request related to a problem?

No

### Description

Hi !

Thanks for this amazing project!
I was able to setup it in less than 3 days.
I made a small script to disable all keyboard keys (except space) to leave it unattended.

Some users asked me to be able to bulk download photos in gallery

Thanks a lot!

### Describe the solution you'd like

Bulk download of photos in gallery
Can be checkboxes and a download button that zip all selected photos.

### Describe alternatives you've considered

I used a Nextcloud plugged to the folder of the photobooth project and a cron to update the db.txt file
So that people can bulk download and can drop photos of the event from their phone at the same time.

I used a small router to make an access point with pihole installed on the machine where photobooth was installed to have a local dns for the gallery and the nextcloud
People download either from a "beautiful" name or a QRCode

**Comment by andi34** [comment]
https://github.com/PhotoboothProject/photobooth/pull/208

Nextcloud integration is WIP and should be available on next release.

**Comment by Rudi-Ment** [comment]
Hi.
At first: Thank you for your very nice project. 
I made a photobooth for the weeding in our family and for the birthdays of our kids.
The responce is allways great !

Is it possible -when you implement the Nextcloud adaptation- to install also an access to PCloud ?
I think PCloud is also a good Cloud-Service...

Best regards

**Comment by andi34** [comment]
Hey and thanks for your request. I am not going to add more cloud services myself. If someone of the community likes to add it I am glad to review needed changes for it. The Nextcloud integration also is a community contribution.

Best regards

Andi

**Comment by floviolleau** [comment]
Hi,

My query is not to add Nextcloud into Photobooth project. It was the alternative I used.
I ask only to allow bulk download in gallery. Please re-read the issue description

Have a good day

**Comment by fmalcher** [comment]
This issue went off as a request for Nextcloud integration. However, coming back to the original idea:
**Could we support a bulk download from the admin interface?** At the moment the only two ways of getting all pictures is through USB Sync or via direct file system access with SSH. Is there anything else I don't know? Thanks! @andi34 

The translation files already contain this string, however it's not in use anywhere:

```
  "download_zip": "Download data folder as zip",
```

**Comment by andi34** [comment]
There was an quite experimental option to download the whole data folder via disk usage page (access via Adminpanel), but I think this got lost while switching to tailwind-css for the admin UI.

For now you could create an own page inside private/ folder of Photobooth to use the endpoint

https://github.com/PhotoboothProject/photobooth/blob/dev/api/diskusage.php

**Comment by andi34** [comment]
Reopened, maybe something to add in future.

**Comment by floviolleau** [comment]
Unstale
