### ISSUE TITLE
[BUG]: Key code which triggers a custom picture

### ISSUE THREAD

**Issue by lagrandeours** [PhotoboothProject/photobooth#253]
### Describe the bug

the custom key code is duplicated from collage key code. it s not possible to make different keycode for collage and custom pictures

### Steps to reproduce the behavior

go to admin change in the admin form values

### Expected behavior

for each Key code which triggers have to be different 'photo' 'collage' and 'custom'

### Photobooth Version

431

### Did it work before?

No

**Comment by andi34** [comment]
Thanks for your report!
Fixed by https://github.com/PhotoboothProject/photobooth/commit/00b0787a1dc0cdc6ce7e1e4b0104c6468e7dde9c
