### ISSUE TITLE
[BUG]: Undefined Variable in keypad screen

### ISSUE THREAD

**Issue by Gefaehrbert** [PhotoboothProject/photobooth#256]
### Describe the bug

When i open the Keypad to log in i get this error:
![image](https://github.com/PhotoboothProject/photobooth/assets/106934888/3ceb8d2e-00ac-4476-958e-2d7dd8fb56a9)

### Steps to reproduce the behavior

Open the keypad

### Expected behavior

no error 

### Photobooth Version

4.3.1 

### Operating System

ubuntu

### Did it work before?

Yes

**Comment by andi34** [comment]
You're on the WIP branch?

**Comment by andi34** [comment]
https://github.com/PhotoboothProject/photobooth/commit/c888a4818cc4b6719911f622d3dfc3a896995d36

This should fix it
