### ISSUE TITLE
[FEATURE]: allow HID remote button on photobooth server 

### ISSUE THREAD

**Issue by mutefiRe** [PhotoboothProject/photobooth#264]
### Is your feature request related to a problem?

Yes

### Description

I'm using an Android Tablet as a screen where a Bluetooth button is connected to. That button triggers the Volume Up key code. However, the browser does not recognize this key code unless I laboriously remap it to another key. This remapping process is not efficient and causes issues for photo booth users who need to type in their email address, as they have to switch between the original keyboard layout and the keymapping app layout.

### Describe the solution you'd like

I would prefer to connect the Bluetooth device to the Raspberry PI where the Photobooth server is running, and have it listen for the key code to trigger whatever is configured. This would create a more centralized solution, eliminating the need for external device configuration.

### Describe alternatives you've considered

ue to the error-prone nature of the current setup, I have considered using the UI buttons on the tablet screen instead.

### Additional context

If you give this a go I would like to contribute on this nice project :)

**Comment by andi34** [comment]
Hey!

I am just about to seperate the remoteBuzzer server optional and allow to use the remoteBuzzer server standalone, e.g. on a Raspberry Pi. The Photobooth itself could be only connected as client to it while running e.g. on a mini PC without GPIO.

Maybe this could be combined?

You're always welcome to fork the source and add new features or fix bugs. Your changes can be submitted for review while opening a Pullrequest.

Best regards

Andi

**Comment by andi34** [comment]
https://github.com/frogro/PhotoboothProject_Pico_as_HID_Button_and_rotary_encoder

https://github.com/frogro/PhotoboothProject_Pico_W_as_remote_button_and_rotary_encoder
