### ISSUE TITLE
Pi Cam V3

### ISSUE THREAD

**Issue by Frontkiller** [PhotoboothProject/photobooth#345]
### Is your feature request related to a problem?

Yes

### Description

Is there a version coming that’s compatible with the Pi cam v3 ?

### Describe the solution you'd like

Make a version that can be used with Pi cam V3

### Describe alternatives you've considered

Pi cam 3 version

**Comment by andi34** [comment]
Photbooth is compatible with the command line interface of libcamera tools, therefore all Pi Camera modules can be used to capture images. If you can capture from command line, it'll also work on Photbooth. Adjust the capture command inside the adminpanel as needed.

The camera not being detected as webcam is an issue of the Pi Foundation and independent of this project. No Pi Cam can be used for preview from device cam using the new camera stack.

To workaround that use the photobooth-app for preview and capture:
https://mgrl.github.io/photobooth-docs/setup/installation/

https://mgrl.github.io/photobooth-docs/reference/photoboothprojectintegration/
