### ISSUE TITLE
[SECURITY]: switch to Node.js v14 or v16

### ISSUE THREAD

**Issue by andi34** [PhotoboothProject/photobooth#40]
### Is your feature request related to a problem?

Yes

### Description

Node.js V12 is not maintained anymore. 

### Describe the solution you'd like

We should upgrade to a Version which is still supported.
Remotebuzzer Server and USB-Sync need to be checked for compatibility.

### Describe alternatives you've considered

None. Must change

**Comment by andi34** [comment]
Node v14.20.1 (LTS)
Or
Node v16.17.1 (LTS)

**Comment by andi34** [comment]
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

GitHub actions need node v16 next year. No date given ATM.

**Comment by mart-e** [comment]
Hi,

FYI Raspberry OS still uses bullseye that offers nodejs 12
https://packages.debian.org/bullseye/nodejs
With a fresh install, I have the following error:
```
### Get yourself a hot beverage. The following step can take up to 15 minutes.
yarn install v1.22.19
[1/5] Validating package.json...
error photobooth@4.3.1: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.22.12"
error Found incompatible module.
```
To install it, I have followed https://techviewleo.com/install-nodejs-and-npm-on-debian-linux/ to install another version.

Maybe it could be a good idea to update [the doc](https://photoboothproject.github.io/Installation-on-Debian) saying 

> If you are using an older version of Rasperry Pi OS or Debian / Debian based distribution Node.js v12.22.x will be installed if needed!

**Comment by andi34** [comment]
@mart-e the docs will be updated soon, didn't found the time yet.
