### ISSUE TITLE
[LOCALIZATION]: 

### ISSUE THREAD

**Issue by UD19971116** [PhotoboothProject/photobooth#411]
### Request a language

Chinese

**Comment by andi34** [comment]
![Screenshot_20231022-101251](https://github.com/PhotoboothProject/photobooth/assets/6080900/3edc45bc-795c-4f41-9620-77bb27f4abc7)


Traditional?

**Comment by andi34** [comment]
It's possible now to join as translator for Chinese (traditional) on crowdin.
