### ISSUE TITLE
[BUG]:  SYNCH to USB not working 

### ISSUE THREAD

**Issue by RickCopithorne** [PhotoboothProject/photobooth#414]
### Describe the bug

Enabling the Synch to USB is not working. Once enabled within the ADMIN console and setting the Config to look for either /dev/sda or the Removable USB Name the files are never synched to the USB drive. 

When looking at the Debug panel I see the following
sh: 1: /usr/bin/node: not found

### Steps to reproduce the behavior

goto http://localhost/admin/
Click Synch Pictures to USB Stick
Under USB Identifier add the location /media/pbadmin/photobooth

### Expected behavior

After the allocated time the new photos should be copied from the Photobooth to the USB stick, 

### Photobooth Version

Latest Version

### Browser and browser version

Chromium 116.0.5845.102

### Operating System

Raspbian Bullseye v11

### Did it work before?

No

**Comment by andi34** [comment]
`sh: 1: /usr/bin/node: not found` means you need to fix the missing library

**Comment by andi34** [comment]
Node path can be defined via Adminpanel.

**Comment by RickCopithorne** [comment]
Will that break anything else ? And this was just a basic install from the documents in Git so what’s the proper path to use ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andi34** [comment]
What's the output of `sudo -u www-data which node` ?

**Comment by RickCopithorne** [comment]
Nothing happens. Once I hit enter it brings me to a new prompt


***@***.***:~ $ sudo -u www-data which node
***@***.***:~ $



Rick Copithorne

Principal Systems Administrator

**Comment by andi34** [comment]
So node is not available, at least not for the www-data user which is running the webserver and running the sync script. You need to get that fixed.

**Comment by RickCopithorne** [comment]
Hate to ask any suggestions? I did enable USB synch during the install and also ran the enable-usb-aynch scripts. ( guessing the name .

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andi34** [comment]
![IMG_20231024_211631_001](https://github.com/PhotoboothProject/photobooth/assets/6080900/9fc902f6-1ab4-42eb-bf2d-2b6334ab88ac)

Your setup must look like this. There's something wrong with your installation.

I'd suggest you try a clean install using latest installer.

**Comment by andi34** [comment]
Or get it fixed while installing node.js in v18
