### ISSUE TITLE
[FEATURE]: generate a Backup file with all Setting

### ISSUE THREAD

**Issue by Notch001** [PhotoboothProject/photobooth#416]
### Is your feature request related to a problem?

No

### Description

Hello, it might be a nice function if you could download a backup file of all the settings and logos, etc. If something happens to the Pi, you can quickly make adjustments

### Describe the solution you'd like

Generate a backup using a button as rar.gz, for example. This file is then downloaded to the end device (tablet or similar). Another button then restores the backup. 

### Describe alternatives you've considered

The alternative would be to take the card out of the Pi and create an image using etcher. But in my opinion that is too complicated

**Comment by andi34** [comment]
Quickly done via command line

```
sudo -u www-data zip -r backup.zip /var/www/html/private/* /var/www/html/config/my.config.inc.php
```

Save the backup.zip where needed 

To restore

```
cd /
sudo -u www-data unzip /path/to/backup.zip
```
