### ISSUE TITLE
[BUG]: Test Collage not working due to errors

### ISSUE THREAD

**Issue by jbcanillo** [PhotoboothProject/photobooth#480]
### Describe the bug

Whenever accessing the localhost/test/collage.php, error occur: 

Warning: Undefined array key "collage" in /var/www/html/src/Factory/CollageConfigFactory.php on line 13
Warning: Trying to access array offset on value of type null in /var/www/html/src/Factory/CollageConfigFactory.php on line 13

Fatal error: Uncaught TypeError: Cannot assign null to property Photobooth\Dto\CollageConfig::$collageLayout of type string in /var/www/html/src/Factory/CollageConfigFactory.php on line 13

Stack trace: #0 /var/www/html/src/Collage.php(16): Photobooth\Factory\CollageConfigFactory::fromConfig() #1 /var/www/html/test/collage.php(43): Photobooth\Collage::createCollage() #2 {main} thrown in /var/www/html/src/Factory/CollageConfigFactory.php on line 13
Installed on Raspberry Pi OS 

### Steps to reproduce the behavior

Go to  localhost/test/collage.php

### Expected behavior

It should load the test preview of the Collage

### Photobooth Version

Latest

### Browser and browser version

Chromium

### Operating System

RPi OS

### Did it work before?

Yes

**Comment by andi34** [comment]
Should be fixed by https://github.com/PhotoboothProject/photobooth/pull/481/files
