### ISSUE TITLE
[BUG]: start page not usable on older devices (network-access)

### ISSUE THREAD

**Issue by Einstein2150** [PhotoboothProject/photobooth#482]
### Describe the bug

Opening the site of the photo box on iOS14 results in a not usable start page
![IMG_0158](https://github.com/PhotoboothProject/photobooth/assets/22019133/b4aafd9f-5d4b-457b-8b48-5abd1645c66c)

### Steps to reproduce the behavior

open Photobox on iOS14 (Safari, Chrome and Firefox)

### Expected behavior

startpage is visible

### Photobooth Version

Installscript/15.11.2023

### Browser and browser version

Safari, Chrome, Firefox

### Operating System

iOS 14

### Did it work before?

?

**Comment by andi34** [comment]
Hey and thanks for your feedback.
Old Browser support is dropped in preparation of the new release and won't be added again. You can stick to latest stable version if it matches your requirements.

Best regards

Andi
