### ISSUE TITLE
[FEATURE]: Shutdownbutton in hidden Admin panel (pre login)

### ISSUE THREAD

**Issue by PWRollo** [PhotoboothProject/photobooth#504]
### Is your feature request related to a problem?

No

### Description

Hello everyone,

great application!

I would welcome a shutdown button in the admin area (before the login page). This way it would be possible for everyone to shut down Photobooth and not just the administrator. Otherwise, the only solution at the moment, in my setup, is to disconnect the power source (power cable).

Many thanks in advance!

Best regards

### Describe the solution you'd like

Shutdown button at the admin panel (pre logon page).

### Describe alternatives you've considered

Unplug powercord

### Additional context

In an older setup, the SD card has become defective - this could be related to power off by disconnecting the power cable

**Comment by andi34** [comment]
You can use the Remotebuzzer Server and trigger shutdown via Gpio connected button or via get request. Via hidden admin shortcut everybody would be able to shutdown if the soft button isn't protected.
