### ISSUE TITLE
[BUG]: Remotebuzzer Server with GPIO on Raspberry Pi 5 not working 

### ISSUE THREAD

**Issue by andi34** [PhotoboothProject/photobooth#528]
### Describe the bug

Currently the Remotebuzzer Server with GPIO on a Raspberry Pi 5 is not supported.

### Steps to reproduce the behavior

Start the Remotebuzzer Server and enable hardware button support.

### Expected behavior

.

### Photobooth Version

Latest

### Operating System

PiOS bookworm

### Did it work before?

No

### Latest working version

None

### Additional context

The syfs interface to control the GPIO is different on a raspberry pi 5. See https://forums.raspberrypi.com/viewtopic.php?t=359302

> For years now, fixing the base GPIO number to zero has been frowned upon by the kernel devs. In the next kernels we release (6.6) there will be an error message at boot up about it. At the same time, the sysfs interface to the GPIOs has been deprecated - some distributions have already disabled it and are expecting users to go through libgpiod.
> The launch of Pi 5 gave us the opportunity to nudge people to update their apps in preparation for the upcoming changes without breaking existing systems. When we launch 6.6 the older Pis will have the same, high-numbered GPIOsn - probably still available by sysfs, but eventually that will be switched off.

The onoff library uses the sysfs interface, which might get deprecated for all Raspberry Pi.

### Raspberry Pi 4 `/boot/firmware/config.txt`
```
# Photobooth
#IN
gpio=5,6,7,8,16,17,20,21,22,26,27=pu
#OUT
gpio=9,10,11,12,18,19,23,24,25=op
# Photobooth End
```
### Raspberry Pi 5 `/boot/firmware/config.txt`
```
# Photobooth
#IN
gpio=404,405,406,407,415,416,419,420,421,425,426,=pu
#OUT
gpio=408,409,410,411,417,418,422,423,424=op
# Photobooth End
```

### Raspberry Pi GPIO sysfs translation

GPIO sysfs Pi 3/4  | GPIO sysfs Pi5  |  PIN  
-------- | -------- | --------
0 (ID_SD)       | 399 | PIN27    
1 (ID_SC)       | 400 | PIN28
2 | 401 | PIN3
3 | 402 | PIN5
4  | 403 | PIN7 
5       | 404 | PIN29
6      | 405 | PIN31     
7       | 406 | PIN26   
8       | 407 | PIN24    
9 |  408 | PIN21    
10          | 409 | PIN19   
11         | 410 | PIN23    
12       | 411 | PIN32    
13       | 412 | PIN33    
14 | 413 | PIN8   
15          | 414 | PIN10    
16      | 415 | PIN36    
17          | 416 | PIN11    
18          | 417 | PIN12    
19      | 418 | PIN35    
20      | 419 | PIN38   
21     | 420 | PIN40    
22          | 421 | PIN15   
23          | 422 | PIN16  
24          | 423 | PIN18  
25         | 424 | PIN22   
26      | 425 | PIN37    
27          | 426 | PIN13

**Comment by maxlin1** [comment]
Here is the Pin Overview, Raspberry Pi 5 Pinouts including GPIO for the 40 Pin Header:

![GPIO-Pi5v14 png-2080x1244](https://github.com/PhotoboothProject/photobooth/assets/10881081/248ceb2e-3b3b-4cda-bf9a-93e10ec1b2eb)

https://community-storage.element14.com/communityserver-components-secureimagefileviewer/telligent/evolution/components/attachments/13/153/00/00/00/14/83/85/GPIO-Pi5v14.png-2080x1244.png?sv=2016-05-31&sr=b&sig=gGhGyYCOO%2FWsyltcEkWawjADIRqSrrv3HJdZBbLTyzU%3D&se=2024-01-10T23%3A59%3A59Z&sp=r&_=IyMgkX+9UuZLmCs//RUL0w==

**Comment by andi34** [comment]
Doesn't help, see post above. Pi5 uses high-value GPIOs on sysfs

**Comment by andi34** [comment]
Instructions have been added to the FAQ.
Installer needs to be adjusted (detect Pi5 and set config.txt accordingly).

How to handle default GPIO setup? Add a pre-defined Pi 5 my.config.inc.php on install? (After resetting it'll be lost).

**Comment by fmalcher** [comment]
@andi34 Thanks for pointing out the differences! What would be the current workaround to get remotebuzzer working on RPI5?

- I added the `gpio` config in `config.txt` for the `4xx` pins (as written in the FAQ and your note above).
- I changed the GPIO numbers in the photobooth config to `4xx` according to your mapping table. `4xx` numbers are visible in the combined config in the Debug Panel.
- Buttons are wired against GND. The whole setup worked fine with a RPI4.
- remotebuzzer is running and accepts GET requests.

remotebuzzer log does not show any errors:

```
[2024-01-09 13:18:52][remotebuzzer][DEBUG] 1142: BUTTON support active
[2024-01-09 13:18:52][remotebuzzer][DEBUG] 1142: Looking for Picture Button on Raspberry GPIO 420
[2024-01-09 13:18:52][remotebuzzer][DEBUG] 1142: Looking for Collage Button on Raspberry GPIO 419
[2024-01-09 13:18:52][remotebuzzer][DEBUG] 1142: Looking for Shutdown Button on Raspberry GPIO 415
[2024-01-09 13:18:52][remotebuzzer][DEBUG] 1142: Looking for Print Button on Raspberry GPIO 425
[2024-01-09 13:18:52][remotebuzzer][DEBUG] 1142: LED for Print Button on Raspberry GPIO 409
[2024-01-09 13:18:52][remotebuzzer][DEBUG] 1142: Initialization completed
[2024-01-09 13:18:52][remotebuzzer][DEBUG] 1142: socket.io server started
[2024-01-09 13:18:52][remotebuzzer][DEBUG] 1142: New client connected - ID Rtompi1cPGfRChb3AAAB
```


Is there anything else I need to do now?
Thanks!


>  Installer needs to be adjusted (detect Pi5 and set config.txt accordingly).

Isn't it possible to use the config.txt filters for this?
Something like this:

```
[all]
gpio=5,6,7,8,16,17,20,21,22,26,27=pu
gpio=9,10,11,12,18,19,23,24,25=op

[pi5]
gpio=404,405,406,407,415,416,419,420,421,425,426=pu
gpio=408,409,410,411,417,418,422,423,424=op

**Comment by andi34** [comment]
Enable experimental settings view and make your adjustments inside the config too

**Comment by fmalcher** [comment]
Thanks for the quick reply! Unfortunately, that doesn't seem to help.
Do you have any other ideas?

![Screenshot 2024-01-09 at 14 37 14](https://github.com/PhotoboothProject/photobooth/assets/1683147/08de5238-b5c3-472c-9ced-314bac60cc42)

**Comment by andi34** [comment]
Old Kernel?
Maybe run an apt update & apt upgrade

**Comment by fmalcher** [comment]
It was a fresh new installation of bookworm 64-bit, so I suppose the kernel version is okay. `apt upgrade` and `apt dist-upgrade` had nothing to install. I can even switch on one of the LEDs through `/sys/class/gpio`, but the remotebuzzer server doesn't want to play with the GPIOs.

Do you have any other hint for me? Maybe I forgot something obvious?
Thanks a lot for your help!

**Comment by andi34** [comment]
What's the output of
```
cat /sys/kernel/debug/gpio
```

About the config.txt I guess I'd do the config via detection of the Pi 5 by `$(tr -d '\0' </proc/device-tree/model)`. We could also use that inside PHP to define the default config.

**Comment by andi34** [comment]
Maybe try a different kernel
```
sudo rpi-update rpi-6.1.y
```
Or
```
sudo rpi-update rpi-6.6.y
```

**Comment by fmalcher** [comment]
Thank you! Unfortunately I didn't get it to work so I assembled it back to a RPI4.
Kernel 6.6 showed a whole different range of GPIO numbers (5xx). An update to the latest patch version of 6.1 didn't work either. `/sys/kernel/debug/gpio` showed the correctly assigned GPIO pins, however remotebuzzer didn't want to react to them.
On the RPI4 with the exact same SD card it worked out-of-the-box. So let's see how this evolves 🙂

**Comment by andi34** [comment]
I need to setup my Pi5 still... But I was told it works. Could you test with one button connected to the GND only please?

**Comment by maxlin1** [comment]
I ran my Pi 5 on Monday again completely according to the instructions on the website and the current PI OS (card reformatted).
It worked great except for one small thing. You have to do a #sudo apt update and sudo apt upgrade manually once. Otherwise you will currently get an npm error. B

**Comment by andi34** [comment]
@maxlin1 why ever the NPM version check wasn't executed again or faulty, it still showed the initial version detected. I've added a recheck this morning slightly different.

It should be enough to run the installer a second time if the error occurs as the update of NPM worked.

I'd be glad if someone can test on a fresh install of pi os and report back.

**Comment by andi34** [comment]
The `apt upgrade` might cause issues for those having the v4l2loopback installed already as it depends on the kernel. Not sure if there'll only be a problem on 32bit PiOS because of the 64bit Kernel used or also on 64bit OS.

Anyway:

You can also add apt update and apt upgrade to the installer by hand if needed.

**Comment by fmalcher** [comment]
Well … 😆 just for fun, I added external pullup resistors, and now everything's fine. The old setup worked perfectly with a RPI4, but something might have changed with RPI5. Once wired with 15kΩ resistors against 3V3 it works with RPI5.
Thanks for all your help!

**Comment by andi34** [comment]
@maxlin1 in case you're able to test a clean I stall on a fresh PiOS Bookworm.

https://gist.github.com/andi34/c162e512aff4315306bfaf3abeac87df


Should set the overlay for Pi 5 inside config.txt and also default config inside Photobooth.

Hopefully really fixes the Problem updated npm not detected.

Both changes are ready for review and need to be tested.

**Comment by andi34** [comment]
@fmalcher lol, most of the time it's detected and logged if it's recommended to add a pull-up resistor.  But glad it works! 

For testing I currently use 

AZDelivery 3 x KY-004 Taster Modul Sensor Taste Kopf Schalter Schlüsselschalter kompatibel mit Arduino und Raspberry Pi inklusive E-Book! https://amzn.eu/d/eydbGja
