### ISSUE TITLE
[FEATURE]: Integration of Cash Interface possible?

### ISSUE THREAD

**Issue by anpa8** [PhotoboothProject/photobooth#561]
### Is your feature request related to a problem?

Yes

### Description

Integrating of payment methods like cash interface
https://casino-software.de/cash-interface2/index_e.htm

### Describe the solution you'd like

Integrate communication with cash interface to accept coins / bills. 
Set amount in admin interface and, if amount is needed for printing and / or make a photo / and a setting for "free"

### Describe alternatives you've considered

-

**Comment by andi34** [comment]
Hey and thanks for your feature request!
I've thought about something like this in the past and added a simple print counter which allows to lock printing after defined amount of prints. Everything else sounds like something for professional use and, from my side, will not be added to this free and OpenSource software. Might be something for a paid plugin in future.
If you like to implement it, you're also welcome to do a pull request with needed changes to the source for review.
