### ISSUE TITLE
Print does not start

### ISSUE THREAD

**Issue by o3liger** [PhotoboothProject/photobooth#585]
### Describe the bug

In the admin panel I switched on the function to print immediately after I took a picture. For any reason a print job is not be generated.
If I try to print from the gallery I'm able to print. 

### Steps to reproduce the behavior

1. Turn on printing after taking a photo
2. Take a photo

### Expected behavior

Start printing job

### Photobooth Version

4.3.1

### Browser and browser version

Chrome 121.0.6167.85 (Offizieller Build) (x86_64)

### Operating System

MacOS

### Did it work before?

Yes

**Comment by andi34** [comment]
Any error visible inside the browser console? (Press F12 to access the console)

**Comment by andi34** [comment]
Also _Allow image filter_ option **must** be disabled to use that function.

**Comment by o3liger** [comment]
Turning off Allow image filter option was the solution! Thank you so much!!
