### ISSUE TITLE
[FEATURE]: Limit how old pictures can be seen in the gallery

### ISSUE THREAD

**Issue by MagnusOstertag** [PhotoboothProject/photobooth#606]
### Is your feature request related to a problem?

Yes

### Description

My photobooth is permanently installed at my place and I take pictures with guests every time someone visits. However, each guest can see the photos of all guests since time immemorial in the gallery. Which is fine for some time back, but not too long.

### Describe the solution you'd like

It would be great, if there would be some setting in the admin panel which allows me to limit the photos shown in the gallery to be `x days` in the past. For example, only the last month.

### Describe alternatives you've considered

I could manually move the older pictures to a separate folder, but this is a hassle and would depend on how often I access the photobooth (which I normally do very seldomly).

**Comment by andi34** [comment]
Hey and thanks for your request.
I am not sure if that's an feature to be implemented. 

Moving files or folders could be easily done via cron job, it's a one time work and would be automated.
Your request would also only be possible if images are named by date.
Another option would be to append a date via config to the defined folders (images , thumbs etc).

@dadav , @benjaminkott , @up-87 any thoughts?

**Comment by up-87** [comment]
It would be possible without any photo naming convention if the metadata of the files was used.
But in general I agree to @andi34 . This is a pretty special use case and nothing that needs to be implemented in photobooth. You could solve this with a script on os startup.

**Comment by dadav** [comment]
It's an interesting feature and a perfect usecase for a cronjob.
I would probably use a command like this:

`find /path/to/images -type f -mtime +1 -exec mv {} /archive \;`

This would move all files older than 1 day to /archive

**Comment by MagnusOstertag** [comment]
Thanks, then I will use a cronjob!
