### ISSUE TITLE
[FEATURE]: Option for naming pictures

### ISSUE THREAD

**Issue by snmabaur** [PhotoboothProject/photobooth#607]
## Intro
Thank you very much for all your work, I appreciate thatg very much

### Is your feature request related to a problem?

No, just a feature

### Description

Use Case:
Use the photobooth in a company for doing all the employee pictures... each employee does the photo itself, confirms the photo and sets the photoname from first/lastname

### Describe the solution you'd like

- An option inside pictures or maybe a new navpoint with a new mode for employee pictures (naming pending ;) )
- Before saving the picture from tmp to pictures folder the user has to confirm it and set a pre- and lastname, non confirmed pictures will stay in `tmp` but not in `picture` folder
- Maybe a helpline like "confirmed pictures will be used in our intranet"
- The photoname should then be something like `lastname_prename_date.jpg`

### Describe alternatives you've considered

Alternative is to check every photo, match it by face and rename it by hand

**Comment by andi34** [comment]
Hey and thanks for your request.
This sounds like an individual solution and nothing really needed imo. We can keep the request open in case we find enough time and a real use-case for everyone.

If you like to implement it in a useful way I am glad to review your changes via Pull request.

Best regards

Andi

**Comment by snmabaur** [comment]
Will do a PR as soon as I have a working code :)

**Comment by snmabaur** [comment]
Hi

I created a local branch `feature/607-rename-image` but don't have the permission to publish a feature branch to create a pull request...

Could you create this banch so I can push into it? Or should I do it in another way?

Thanks and cheers ;)
