### ISSUE TITLE
"File was not created" when I try to take a photo

### ISSUE THREAD

**Issue by Louloubiwan** [PhotoboothProject/photobooth#631]
### Describe the bug

**Hello everyone !**

So when I try to take a photo, everything seems working (5..4..3..2..1..) with the preview, but after I get the error who said The file was not created, but how to assigne the file ? (I think is the file were the photo are supposed to be)

If anyone can give me information, I will be thanksfull !

### Steps to reproduce the behavior

1. Go to photo
2. Take the photo
3. Wait the couldown 
4. the bug message appears

### Expected behavior

Up 👆

### Photobooth Version

4.4.0

### Browser and browser version

FireFox

### Operating System

Raspberry pi imager (the last one)

### Did it work before?

No

### Latest working version

no

### Additional context

_no_

**Comment by andi34** [comment]
If you're having issue on the setup you're welcome to join our community @ telegram. To get help make sure to post enough information, e.g your commands and preview config.
