### ISSUE TITLE
[FEATURE]: Video Background

### ISSUE THREAD

**Issue by mimagoo** [PhotoboothProject/photobooth#641]
### Is your feature request related to a problem?

No

### Description

it would be nice if I had the option to use a video file as a background instead of the background images. incl. uploading videos. 

### Describe the solution you'd like

in admin backend a switch to select if video or still image as background.
in admin backend a possibility to upload videofiles .mp4 up to 4K

### Describe alternatives you've considered

Alternatively the possibility to set a livestream (youtube) as background.

**Comment by gitChriss** [comment]
Oh. I would love that feature!
