### ISSUE TITLE
[BUG]: Image frame not working

### ISSUE THREAD

**Issue by ZaRdoOx** [PhotoboothProject/photobooth#642]
### Describe the bug

when i select take picture with frame it automatically reboot the photobooth but the path of the frame is correct and im using the release 4.4.0

### Steps to reproduce the behavior

1. click take pic with frame
2. take picture
3. photobooth error

### Expected behavior

when i select take picture with frame it automatically reboot the photobooth but the path of the frame is correct and im using the release 4.4.0

### Photobooth Version

4.4.0

### Browser and browser version

chrome and firefox

### Operating System

windows 11

### Did it work before?

No

**Comment by andi34** [comment]
More information about your setup needed.
OS Photobooth installed on?
PHP version?

**Comment by ZaRdoOx** [comment]
> More information about your setup needed. OS Photobooth installed on? PHP version?

Hello ! 

PHP Version 8.2.13

Apache 2.4

OS : Windows 11 

I'am using a Wampserver to run the photobooth

[error.log](https://github.com/PhotoboothProject/photobooth/files/14691986/error.log) but no error that mean frame isn't working

**Comment by andi34** [comment]
Still need to look at. Busy in real life currently.

**Comment by sibr1234** [comment]
For me adding image frames doesn't work either. In the log i found the following:
Error ["Can't create GD resource.","Failed to create frame from image."]
This leads me to image.php and the function call imagcreatetofromstring(). Unfortunately i never did anything with php until now and don't know how to debug...
Thanks for helping

**Comment by andi34** [comment]
How does your config look like?
Until v4.4.1 frame needed to be a full path while on latest development version it must be placed inside the Webserver.
Example until v4.4.1
```
/var/www/html/resources/img/frames/frame.png
```
Example on latest development version:
```
/resources/img/frames/frame.png
```

**Comment by andi34** [comment]
And if it's failing with `Can't create GD resource` there might be something wrong with your image file.

**Comment by andi34** [comment]
![Screenshot_20240826-064557](https://github.com/user-attachments/assets/6c9dd799-bada-45ce-bc5b-75594ca58a0a)


At least on Linux I also can't confirm a bug on v4.4 0/v4.4.1

**Comment by sibr1234** [comment]
I am running on RPI5 with 8 Gb RAM. Installed using the install-photobooth script (version 4.99). PHP version is 8.3.10.
I tried it with the demo image and one of the provided frames in the webserver directory

**Comment by andi34** [comment]
![Screenshot_20240826-202205](https://github.com/user-attachments/assets/1e80cee0-8d9e-4c49-89dd-c0ffc09c29e8)
![Screenshot_20240826-202107](https://github.com/user-attachments/assets/3ccf3011-5807-42c0-9dcb-f2a335fe8d63)


PHP 8.2, frame with and without extension

**Comment by andi34** [comment]
Same with php 8.3.10
![Uploading Screenshot_20240826-202946.png…]()

**Comment by andi34** [comment]
Same with pho 8.3.10
![Screenshot_20240826-202946](https://github.com/user-attachments/assets/173e6e72-55b5-4834-ae74-8cdcfa196158)

**Comment by sibr1234** [comment]
I did a clean reinstall and now it works perfectly. Unfortunately i cannot replicate what the problem was.
 Thanks for your help! Appreciate it a lot!

**Comment by sevensolutions** [comment]
I had the same problem.
The problem was that my camera (EOS 80D) was configured to take a RAW and JPEG photo and Photobooth downloaded the raw file instead of the jpeg.
Turning off RAW solved the problem.
Just in case someone finds this issue and having the same problem.
