### ISSUE TITLE
[BUG]: First photo shot only working after restart of browser

### ISSUE THREAD

**Issue by timo619** [PhotoboothProject/photobooth#667]
### Describe the bug

After booting the system and autostart of the browser the first photo loads the live preview but ends in an error after the countdown and stays there. Automatic restart of photobooth software is not working. When I manually close the browser and open it again, the photobooth software works as expected. 

### Steps to reproduce the behavior

1. Reboot, wait for browser to open
2. take picture --> failes after countdown
3. Restart browser --> works

### Expected behavior

Taking a photo without error

### Photobooth Version

latest version from 04.04.2024

### Browser and browser version

Firefox 116.0.2

### Operating System

Ubuntu on Dell thin client

### Did it work before?

Yes

**Comment by andi34** [comment]
Related to https://github.com/PhotoboothProject/photobooth/issues/527
