### ISSUE TITLE
[BUG] Rewrite RemoteBuzzer server to avoid use of sysfs on kernel 6.6 and higher

### ISSUE THREAD

**Issue by jacques42** [PhotoboothProject/photobooth#682]
### Describe the bug

sysfs is depreciated and has been removed from kernel 6.6 onwards. Rewrite RemoteBuzzer server in Python3

### Steps to reproduce the behavior

Top reproduce, install on system with kernel 6.6 or higher 

### Expected behavior

Remote Buzzer works on kernel 6.6 and higher

### Photobooth Version

All

### Did it work before?

Yes

**Comment by andi34** [comment]
Unstale. Any news on this @jacques42 ?
