### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by AlexXLVI** [PhotoboothProject/photobooth#694]
### Describe the bug

All collages have a resolution of 96 dpi. The configuration of 300 dpi in the admin panel is ignored. Both for the existing collages and for the ones you configured yourself via json.

### Steps to reproduce the behavior

Changes in the configuration in the Adminpanel are ignored.

### Expected behavior

The result of the collage should have at least 300 dpi as standard.

### Photobooth Version

4.4.0

### Browser and browser version

Firefox

### Operating System

PIOS Bookworm 64

### Did it work before?

Yes

### Latest working version

unknown

**Comment by andi34** [comment]
Please update to latest development version and reopen the issue if there's still a problem.
Please verify the image dimensions of the collage inside /var/www/html/data/images
