### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by thetechnikfreak** [PhotoboothProject/photobooth#706]
### Describe the bug

I cant Open the Photobooth: Fatal error: Uncaught Exception: Database or
path is not writable: /var/www/html/data/mail-
adresses.txt in
/var/www/html/src/Service/MailService.php:12
Stack trace: #0 /var/www/html/lib/boot.php(76)
Photobooth\Service\MailService->__construct()
#1 /var/www/html/index.php(3): require_once('...
#2 /main, thrown in
/var/www/html/src/Service/MailService.php on Line 12
![20240516_181038](https://github.com/PhotoboothProject/photobooth/assets/95089272/462ef61d-cc39-4060-ad05-f845a2d3dec5)

### Steps to reproduce the behavior

Do a fresh install of the Photobooth 

### Expected behavior

IT to work

### Photobooth Version

Newest

### Browser and browser version

Chromium newest

### Operating System

Raspi os

### Did it work before?

Yes

### Latest working version

Before fresh install

**Comment by andi34** [comment]
You've used the installer?
The installer should set the permissions right by default.

**Comment by fmiccolis** [comment]
I have the same problem on my machines (Windows 10 and 11) both initialized on WSL2 following the guide on [here](https://photoboothproject.github.io/install/install-windows/).

Could be useful to know that also the capture command does not work:
![Capture](https://github.com/PhotoboothProject/photobooth/assets/60185179/071c19d1-6315-476a-8cf7-08022ed80651)

**Comment by thetechnikfreak** [comment]
> You've used the installer?
> The installer should set the permissions right by default.

Yes in tried IT with the Installer wich Not worked and then deleted IT and did It with the Manual Check on the Guide on GitHub.io wich didn't work ether

**Comment by thetechnikfreak** [comment]
Plus Informationen: Im on a raspi 4 and i Open the Admin and the Home Page and IT didn't work

**Comment by andi34** [comment]
```sh
sudo chown -R www-data:www-data /var/www/html
```
Guess You've missed to set permissions for the www-data user

**Comment by andi34** [comment]
Might be related to https://github.com/PhotoboothProject/photobooth/pull/704 , looks like folders are not created ATM

**Comment by thetechnikfreak** [comment]
So i Reinstall IT witz the new Version via the Install Script but i Had still to run the permision command
