### ISSUE TITLE
[invalid] Live view not working

### ISSUE THREAD

**Issue by tdonhauser** [PhotoboothProject/photobooth#80]
### Describe the bug

I try to use the live view feature with my EOS 500D, but the picture won't light up in the backround. I'm using the newest version. I hear the mirror of the camera clicking, but it immidialty goes back and no live view is visible.

### Steps to reproduce the behavior

If I run `python3 cameracontrol.py --bsm` the following error shows up:

![grafik](https://user-images.githubusercontent.com/21998742/199609599-1d007416-d240-44a3-a33e-77d89b6a5558.png)

### Expected behavior

The live view should be visible in the background during picture taking.

### Photobooth Version

latest

### Did it work before?

No

**Comment by andi34** [comment]
Hey and thanks for your report.
You don't have the GPhoto2 video Interface which will be used.
See the error you posted:

```
unable to open V4L2 device '/dev/video0'
```
That's not an issue of Photobooth, it's an issue of your setup.

Have you installed the service as described in the FAQ?
If not, you should follow the steps mentioned in the FAQ. https://photoboothproject.github.io/FAQ#preview-from-dslr

If yes, you might need to fix the kernel module yourself.

### Fix v4l2loopback Module

Open a terminal and run the following commands:

```sh
curl -LO https://github.com/umlaeute/v4l2loopback/archive/refs/tags/v0.12.7.tar.gz
tar xzf v0.12.7.tar.gz && cd v4l2loopback-0.12.7
make && sudo make install
sudo depmod -a
sudo modprobe v4l2loopback exclusive_caps=1 card_label="GPhoto2 Webcam"
```

Now check if everything is fine:
```sh
sudo v4l2-ctl --list-devices
```

If it didn't worked, you get the following response:

```
Cannot open device /dev/video0, exiting
```

If it worked, you get the following response:

```
GPhoto2 Webcam (platform:v4l2loopback-000):

        /dev/video0
```

**Comment by tdonhauser** [comment]
Thanks a lot! This works.

**Comment by andi34** [comment]
👍 great. I'll add a note to the update instructions asap. Maybe we should by default compile the module by ourselves.
But independent of the Photobooth Update: it always need to be re-done if the kernel gets updated on the system (regular System Update).

**Comment by andi34** [comment]
https://github.com/PhotoboothProject/PhotoboothProject.github.io/commit/c3310f812799cc7dc1bdd40229d3923c539ac902
