### ISSUE TITLE
[FEATURE]: Fullscreen Mode

### ISSUE THREAD

**Issue by DunkinDonat** [PhotoboothProject/photobooth#831]
### Is your feature request related to a problem?

Yes

### Description

I have an old tablet that I use to run the photobooth in the fotobox. Unfortunately, there are no updates available for the Chrome web browser. When I start the photobooth with that tablet, it opens a broken web app. Fully Kiosk Browser doesn't work either. Only Firefox works on it, as I can get the latest version of Firefox. With Firefox, it works excellently.

To get rid of the address bar, I found the fullscreen mode in the settings. However, you can only activate it by allowing a button to appear on the home screen. It's not ideal to have it there. I think there is also a bug. If you take a picture in fullscreen mode, you will see the preview. After the timeout, it goes back to the home screen and exits fullscreen mode. It would be nice to have it always on and without the button on the homepage.

### Describe the solution you'd like

Please make the fullscreen mode always-on setting configurable.

### Describe alternatives you've considered

The toogle button on the homepage.

**Comment by andi34** [comment]
That's a browser limitation and needs the user to trigger the full screen mode. Afaik this can not be done automatically.

**Comment by andi34** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen

> ## Security
> Transient user activation is required. The user has to interact with the page or a UI element in order for this feature to work.
