### ISSUE TITLE
Printing isnt working

### ISSUE THREAD

**Issue by thetechnikfreak** [PhotoboothProject/photobooth#877]
### Describe the bug

I cant Print the printer is connected and select as Standart printer using LP when i Print with Raspberry ui its working but Not via the cmd it Starts the Connection but transmits Zero Bytes after Testing around i found Out that the only Thing that inst working is printing jpgs via the cmd i dont know why

### Steps to reproduce the behavior

Print

### Expected behavior

Print

### Photobooth Version

4.99

### Browser and browser version

Chrome

### Operating System

Raspberry, Windows,Androt

### Did it work before?

No

**Comment by andi34** [comment]
Make sure printer is shared. 
Maybe run `sudo cupsctl --share-printers` via terminal.

On Canon selphy printer it's important to use latest firmware.

Another issue might be Gutenprint or cups which might need an update.

All of possible issues are not related to Photobooth itself and OS / OS Setup related.

**Comment by andi34** [comment]
In case firmware is up to date and sharing printer via cmd or via cups doesn't solve your problem:

https://www.peachyphotos.com/blog/stories/building-modern-gutenprint


If updating Gutenprint also does not work, compile cups yourself from latest **2.4x branch (!)**

https://github.com/OpenPrinting/cups/blob/2.4.x/INSTALL.md

**Comment by thetechnikfreak** [comment]
Didnt Work for me at all  (Printer for testing Canon ts8351)

First i gave the fotobooth User group root Access with
```
sudo usermode -aG sudo www-data
``` 

Then I Set this cmd as the cmd for printing in the Admin menü (IT doesnt Work when you do it throw the cmd)
And Print a random Image throw photobooth
```
lpoptions -d printernane
```
(You can find the Printername when you run this cmd in the cmd line
```
lpstat -p
```
)

At the end Set this cmd as your cmd for printing in the Admin Panel and IT should work
```
convert %s tempfile.png && lp -o landscape tempfile.png && rm tempfile.png
```
