### ISSUE TITLE
[BUG]: Print button when results buttons disabled

### ISSUE THREAD

**Issue by theamnesic** [PhotoboothProject/photobooth#881]
### Describe the bug

The Print button still appear in the result page even when RESULT_BUTTONS is disabled.

### Steps to reproduce the behavior

Disable `result_buttons` in user interface settings.
Enable `print_from_result` from the printing settings.

### Expected behavior

The print button is hidden.
I'm using a custom keyboard for Collage and Printer, so I just need Collage, QR and Print enabled, with no buttons.

### Photobooth Version

Up-to-date

### Browser and browser version

Firefox up to date

### Operating System

Ubuntu 24.04

### Did it work before?

Yes

**Comment by andi34** [comment]
Like you've noticed, print is handled independent. Button bar config handles the following buttons:
- take picture
- take collage 
- take video
- galllery
- Email 
- qr code

You can anyway hide the button using a own overrides.css inside the private folder of your Photobooth installation.

**Comment by theamnesic** [comment]
Didn't know for `overrides.css` feature, thanks!

**Comment by andi34** [comment]
I guess the key code trigger part should be revisited before the next major release as some actions use different API endpoints while on print we need to simulate a button press.

Maybe I need to add some extra checks to also prevent taking new images, collage or video on result screen if the button bar is disabled.
