### ISSUE TITLE
[FEATURE]: Custom force_buzzer message option

### ISSUE THREAD

**Issue by theamnesic** [PhotoboothProject/photobooth#882]
### Is your feature request related to a problem?

No

### Description

When enabling `force_buzzer` on the Home settings, `Use Buzzer to take a Picture` appear.

### Describe the solution you'd like

Hide or customize the message.

### Describe alternatives you've considered

Checkbox in the admin panel.

**Comment by andi34** [comment]
Accepted. I'll take a look sometimes in October.
