### ISSUE TITLE
[FEATURE]: Export/Import function for config

### ISSUE THREAD

**Issue by Raukze** [PhotoboothProject/photobooth#96]
### Is your feature request related to a problem?

No

### Description

It takes a lot of time to setup the configuration for the photobooth if you're not using mostly default settings and for testing purposes I don't have the option to easily get another instance running with the same config.

### Describe the solution you'd like

In the admin panel I'd wish to have an option to download the current config (backup) and upload an existing config (new instance or restore).

### Describe alternatives you've considered

If I have access to the shell I could copy over the config file from one system to the other but I find it more comfortable to have a way to do this from the frontend.

**Comment by andi34** [comment]
Hey and thanks for the suggestion!
I'll add it to my personal notes, I guess this could be implemented along with the upload of own backgrounds, fonts and whatever. But it hasn't a high priority for me at the moment, there's general code I'd like to improve in the limited time I currently have for this project.
