### ISSUE TITLE
[FEATURE]: Print only QR Code

### ISSUE THREAD

**Issue by Tho-Gra** [PhotoboothProject/photobooth#976]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Is it maybe possible to create on the administration site a button, where I can choose the point to print only the QR Code, without picture.

### Describe alternatives you've considered

Alternative I could print the QR Code with the picture together... but this is not, what I want...

### Additional context

I want to print the QR Code over a thermal printer (like on a supermarket)

**Comment by andi34** [comment]
Hey and thanks for your request.
Currently I think this is an individual use case and nothing a wide range of user will use or benefit from. You can modify the code and use an own custom post processing, e.g. using private/api/print.php introduced in https://github.com/PhotoboothProject/photobooth/pull/969 .
